config/routes.rb
Rails.application.routes.draw do
  # get 'doses/index'
  # get 'doses/new'
  # get 'doses/create'
  # get 'doses/destroy'
  # get 'cocktails/index'
  # get 'cocktails/show'
  # get 'cocktails/new'
  # get 'cocktails/create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # A user can see the list of cocktails
  # GET "cocktails"
  # A user can see the details of a given cocktail, with the dose needed for each ingredient
  # GET "cocktails/42"
  # A user can create a new cocktail
  # GET "cocktails/new"
  # POST "cocktails"
  resources :cocktails, only: [:index, :show, :new, :create] do
    resources :doses, only: [:new, :create]
  end
  resources :doses, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  has_one_attached :photo
  validates(:name, uniqueness: true, presence: true)
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates(:description, presence: true)
  validates_uniqueness_of :ingredient, scope: :cocktail
  # validates :cocktail, uniqueness: { scope: :ingredient }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  has_many :cocktails, through: :doses
  validates(:name, uniqueness: true, presence: true)
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    # GET /cocktails
    @cocktails = Cocktail.all
  end

  def show
    # GET /cocktails/:id
    @cocktail = Cocktail.find(params[:id])
    @dose = Dose.new
  end

  def new
    # GET /cocktails/new
    @cocktail = Cocktail.new
  end

  def create
    # POST /cocktails
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      # no need for app/views/cocktails/create.html.erb
      redirect_to cocktail_path(@cocktail)
      # cocktail GET  /cocktails/:id(.:format)
      # cocktails#show
    else
      # redirect_to new_cocktail_path
      render :new
      # render 'new'
    end
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def new
    set_cocktail
    @dose = Dose.new
  end

  def create
    set_cocktail
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail)
      #  cocktail_doses GET    /cocktails/:cocktail_id/doses(.:format)
      # doses#index
      # POST   /cocktails/:cocktail_id/doses(.:format)
      # doses#create
    else
      render :new
    end
  end
  # DELETE /cocktails/:cocktail_id/doses/:id

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to cocktail_path(@dose.cocktail)
  end

  private

  def set_cocktail
    # *Strong params*: You need to *whitelist* what can be updated by the user
    # Never trust user data!
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
  # "description"
  # "cocktail_id"
  # "ingredient_id"
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/index.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('<%= image_path 'cocktails-at-sunset.jpg' %>');">
  <div class="banner-content">
    <h1>Cocktails</h1>
    <%= link_to "Add new cocktail", new_cocktail_path, class: "btn btn-primary btn-lg" %>

  </div>
</div>
<div class="container">
  <div class="row">
    <% @cocktails.each do |cocktail| %>
      <div class="col-12 col-md-6 col-lg-3">
        <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url(<%= cl_image_path cocktail.photo.key %>);">
          <div class="card-description">
            <h2><%= link_to "#{cocktail.name}", cocktail_path(cocktail.id) %></h2>
            <!-- <h3>Ingredients:</h3>
            <p><%= cocktail.doses %> <%= cocktail.ingredients %></p> -->
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/cocktails/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <h1>Create a new cocktail</h1>

      <%= simple_form_for @cocktail do |f| %>
        <%= f.input :name %>
        <%= f.input :photo, as: :file %>
        <%= f.button :submit, class: 'btn btn-primary' %>
      <% end %>
      <p><%= link_to "Go back", cocktails_path, class: "btn btn-primary btn-lg" %></p>
    </div>
  </div>
</div>

app/views/cocktails/show.html.erb
<div class="container">
  <h1><%= @cocktail.name %></h1>
  <%= cl_image_tag @cocktail.photo.key, height: 300, width: 400, crop: :fill %>
  <div class="row">
    <div class="col-sm-12 col-md-6">
      <h2>Recipe</h2>
      <table class="table table-bordered">
        <tbody>
          <thead>
            <th>Ingredient</th>
            <th>Description</th>
            <th>Action</th>
          </thead>
          <% @cocktail.doses.each do |dose| %>
            <tr>
              <td><%= dose.ingredient.name %></td>
              <td><%= dose.description %></td>
              <td>
                <%= link_to dose_path(dose), method: :delete, data: { confirm: "Are you sure?" } do %>
                  <i class="fa fa-trash destroy_dose"></i>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  <div class="col-sm-12 col-md-6">
    <!-- _new.html.rb - added underscore to work - required whenever rendering a partial -->
    <!-- rendering page within the page -->
    <%= render 'doses/new', cocktail: @cocktail, dose: @dose %>
    <br>
    <p><%= link_to "Go back", cocktails_path, class: "btn btn-primary" %></p>
  </div>

</div>

<!-- new_cocktail_dose_path -->

  <!-- iteration cocktail.doses.each do |dose|
  dose.description
  dose.ingredient.name
  link_to "delete dose"
  link_to Add dose
   end -->

app/views/doses/_new.html.erb
<h3>Add a new dose</h3>
<%= simple_form_for [cocktail, dose] do |f| %>
  <%= f.association :ingredient, input_html: { class: "beautiful-dropdown" }, include_hidden: false %>
  <%= f.input :description %>
  <%= f.button :submit, class: "btn btn-primary" %>
<% end %>
<!-- form that allows to add ingredients and dose description -->
<!-- this is the only one we need -->

app/views/doses/new.html.erb
<h1>Doses#new</h1>
<p>Find me in app/views/doses/new.html.erb</p>
<!-- form that allows to add ingredients and dose description -->
<!-- this is the only one we need -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <!-- from app/assets/javascripts/application.js -->
    <%= javascript_include_tag "application" %>
    <!-- from app/javascript/packs/application.js -->
    <%= javascript_pack_tag "application" %>
  </body>
</html>